language: generic

sudo: false

cache:
  apt: true

addons:
  apt:
    packages:
      - gcc-5
      - gfortran-5
    sources:
      - ubuntu-toolchain-r-test

install: make FC=gfortran-5

script:
  - ./parseargs
  - ./parseargs 4 5
  - ./parseargs i=4 j=5
  - ./parseargs j=4 i=5
