language: generic

sudo: false

cache:
  apt: true

addons:
  apt:
    packages:
      - gfortran-5
      - gfortran-6
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

env:
- FC=gfortran-5
- FC=gfortran-6

install: make

script:
  - ./parseargs
  - valgrind --error-exitcode=1 --leak-check=full ./parseargs
  - valgrind --error-exitcode=1 --leak-check=full ./parseargs i=4 j=5
  - valgrind --error-exitcode=1 --leak-check=full ./parseargs j=4 i=5
